language: python
branches:
  only:
  - master
  - /^v.*$/
services:
- docker
python:
- 3.6
install: docker-compose build test
script: docker-compose run test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ecurtin2
  password:
    secure: dFhDb3SKutfEGltja8IynzDeDzbusuxltnzE0sEYCGc2Vq20KwSo9HeSsD/TaqU62U2yTBSLigUQiBPLkOOJmYZhxar7HiUlQAo/K5WVx4tEf/i05ru3jqGQ4BE0IQv2uOjLJl/UXRdSPjJJoxWiGvGDyWUeec5Dz1+lIkqbkorKa/jFMyqw9tEp8yOrwPIAGgCtqDw8pfV1JZTxQO/6Mgjv5on5PlrMVfcLH+hfB4VRAPuYfdNtdkapXUmBZnyFStNUpt3y86TV5wHifTWCYSQQXcBj7vliO+uxeZhG+ArhOQWiKA88chCH36mFfd7nd72+nO228cJ/LR3MQ8Gr4x+920KLi52RCsG2Y3HHv7HP0OWeqvBEOmVPj7k8+26Dv0BfJgpIVdwR0WnVRTxJLQbCcBW+EvihIaaaZDiNVXgXBvFCtj4Xz/Qb5YN/Hu7+Wtg1fISH4ZqmA2YlG6b7zkaqgSwHsVvFs5v9rZOKUHz2fkqsMe1wCo+AvkvaweVeNHjxU7jOVU6oEx5c3HQ6Ljgr3L+FAwl6f8FxcQv6rZil4oiIarfDQr4Bx6VpeMmLEJa4Cy6LeLGNzWdaQ3u3Q7RR4kVNi+xH1j3MvRn6xlaEz7wr2G8kNjTHsA83M3mrcLxKPts9fmu0DDkKa2XDbOt5SERVyYjXDe4JY2hpnrQ=
  on:
    python: 3.6
    skip_existing: true
