site_name: Transit-Chem
nav:
  - Home: index.md
  - About: about.md
  - "Getting Started": getting-started.md
  - Tutorials:
    - "The Triple Well Potential": tutorials/triple_well.ipynb
    - "Harmonic Oscillator Basis Functions": tutorials/oned_basis.ipynb
    - "Operators": tutorials/operators.ipynb
    - "Time Independent Schroedinger Equation": tutorials/time_independent.ipynb
    - "Time Dependent Schroedinger Equation": tutorials/time_dependence.ipynb
    - "Transition Matrix": tutorials/transition_matrix.ipynb
    - "Probability of Non-Sampling (Pnot)": tutorials/pnot.ipynb
    - "Putting it all together": tutorials/all.ipynb
  - 'API Documentation': apidoc.md
  - License: LICENSE.md
  - Citing: citing.md
  - Contribute: contribute.md


theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'amber'

extra_css: [extra.css]

repo_name: 'ecurtin2/transit-chem'
repo_url: 'https://github.com/ecurtin2/transit-chem'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ecurtin2'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/evanmcurtin'

  search:
    languge: 'en'


plugins:
  - mkdocs-jupyter