site_name: Quantized
nav:
  - Home: README.ipynb
  - About: about.md
  - "Getting Started": getting-started.md
  - Tutorials:
    - "The Triple Well Potential": tutorials/triple_well.ipynb
    - "Harmonic Oscillator Basis Functions": tutorials/oned_basis.ipynb
    - "Operators": tutorials/operators.ipynb
    - "Time Independent Schroedinger Equation": tutorials/time_independent.ipynb
    - "Time Dependent Schroedinger Equation": tutorials/time_dependence.ipynb
    - "Transition Matrix and Pnot": tutorials/transition_matrix.ipynb
    - "Putting it all together": tutorials/all.ipynb
  - 'API Documentation':
    - "Atom": api_docs/atom.md
    - "Basis": api_docs/basis.md
    - "Configuration": api_docs/config.md
    - "Elements": api_docs/elements.md
    - "Hopping Matrix": api_docs/hopping_matrix.md
    - "Molecule": api_docs/molecule.md
    - "Operators": api_docs/operators.md
    - "Potentials": api_docs/potentials.md
    - "Time Evolution": api_docs/time_evolution.md
    - "Utilities": api_docs/utils.md
    - "Validation": api_docs/validation.md
  - License: LICENSE.md
  - Citing: citing.md
  - Contribute: contribute.md


theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'amber'

extra_css: [extra.css]

repo_name: 'ecurtin2/quantized'
repo_url: 'https://github.com/ecurtin2/quantized'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ecurtin2'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/evanmcurtin'

plugins:
  - mkdocs-jupyter
  - mkdocs_apidoc
