name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build and publish
      uses: abatilo/actions-poetry@v1.0.0
      with:
        args: ["poetry", "publish", "-u", "$PYPI_USERNAME", "-p", "$PYPI_PASSWORD", "--build"]
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

